title: Peers Touch Documentation
description: A comprehensive documentation site for Peers Touch
url: "http://localhost:4000"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Internationalization
languages: ['en', 'zh']
default_lang: 'en'
exclude_from_localization: ['assets', 'images', 'css', 'js']

# Plugins
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Navigation (will be translated via i18n data)
navigation:
  - key: nav.overview
    url: /docs/overview/
  - key: nav.technical
    url: /docs/technical/
  - key: nav.product
    url: /docs/product/
  - key: nav.examples
    url: /docs/examples/

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/