services:
  jekyll:
    image: jekyll/jekyll:latest
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
    command: sh -c "bundle install && jekyll serve --watch --drafts --force_polling --host 0.0.0.0 --port 4000 --trace"